FROM golang:1.23.2 as builder
WORKDIR /app
COPY ./go.mod ./go.sum ./
RUN go mod download
COPY ./ ./
RUN make build-webrtc

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/bin .
EXPOSE 3478/udp
EXPOSE 3478/tcp
CMD ["./chattify-turn"]
